config/routes.rb
Rails.application.routes.draw do

  namespace :auth do
    namespace :users do
      get 'registrations/new'
    end
  end
  devise_for :users, controllers: {
    sessions:      'auth/users/sessions',
    registrations: 'auth/users/registrations'
  }

  as :user do
    get '/login', to: 'auth/users/sessions#new'
  end

  scope module: 'app' do
    resources :pages, only: [:show]
    resources :destinations, only: [:create]
    resources :keywords

    namespace :community do
      resource :keywords, only: [:show]
      resources :categories, only: [:show]
    end
  end

  get '/test', to: 'app/pages#test_page'

  root to: 'app/pages#show'
end

app/views/app/pages/show.html.erb
<!--home page-->
<!-- Masthead -->
<header class="text-center">
  <div class="container">
    <div class="row">

      <div class="col-xl-9 mx-auto mb-5">
        <% if current_account %>
        <div class="mb-2"><h3 class="mb-0 text-muted">:: Search ::</h3></div>
      <% else %>
          <h1 class="mb-5 text-muted mt-5">
            Search websites directly using your own shortcut keywords!
          </h1>
          <p class="text-muted small">
            Go ahead, give it a try!
            Enter <strong><i>yt star wars</i></strong> below
            to search on YouTube for Star Wars videos!
          </p>
      <% end %>
      </div>

      <div class="col-md-10 col-lg-8 col-xl-7 mx-auto mb-3">
        <%= form_tag '/destinations', method: 'post', class: "search-box" do %>
          <div class="form-row">

            <%= text_field_tag 'destination[terms]',
                               nil,
                               id:           "search-field",
                               class:        "form-control left-border-radius",
                               autocomplete: 'off'
            %>
            <button id="search-button" class="right-border-radius" type="submit">
              <i class="fa fa-search float-right pr-3"></i>
            </button>

          </div>
        <% end %>
      </div>
    </div>
  </div>
</header>


<section class="bg-grey text-center pb-5">
  <div class="container">
    <div class="row">
      <div class="col-10 mx-auto">

        <div class="accordion" id="accordionKeywords">
          <div class="card" id="keyword-card">
            <div class="card-header" id="headingKeywords">
              <h2 class="mb-0">
                <button class="btn btn-link"
                        type="button"
                        data-toggle="<%= current_account ? '' : 'collapse' %>"
                        data-target="#collapseKeywords"
                        aria-expanded="true"
                        aria-controls="collapseKeywords">
                  <%= current_account ? '' : 'Check out some available keywords' %>
                </button>
              </h2>
            </div>

            <div id="collapseKeywords"
                 class="<%= current_account ? '' : 'collapse' %>"
                 aria-labelledby="headingKeywords"
                 data-parent="#accordionKeywords">
              <div class="card-body">

                <div class="row">
                  <div class="col-12 mb-3">
                    <% unless current_account %>
                      Quickly search these websites using their keywords!
                      <br>
                      <%= link_to 'Sign up', new_user_registration_path %> to create your own and
                      <%= link_to 'discover more', community_keywords_path %> more from the community.
                    <% end %>
                  </div>
                </div>

                <% if @keywords.empty? %>
                  <div class="row mb-2">
                    <div class="col-12">
                      Looks like you don't have any keywords!
                      <br><br>
                      To begin, <%= link_to 'create your own keywords', new_keyword_path %>
                      or add keywords shared by other members of the
                      <%= link_to 'community', community_keywords_path %>.
                    </div>
                  </div>
                <% end %>

                <% if @keywords.present? %>
                  <% if current_account %>
                    <div class="row mb-2">
                      <div class="col-12 small text-right mb-1">
                        <%= link_to 'Add new keyword', new_keyword_path, style: 'float: right', class: 'mr-3' %>
                      </div>
                    </div>
                  <% end %>

                  <div class="d-flex bd-highlight flex-wrap">
                    <% @keywords.group_by(&:category).each do |category, keywords| %>
                        <div class="p-2 flex-fill bd-highlight col-lg-4 col-md-4 col-xs-12 mb-4">
                          <div class="row"><!-- title div -->
                            <div class="col">

                              <a href="#category-list-<%= category.id %>" data-toggle="collapse">

                                <div class="category-title">
                                  <div class="row">
                                    <div class="col-2">
                                      <i class="fas fa-plus fa-small"></i></div>
                                    <div class="col-8"><%= category.title %></div>
                                  </div>
                                </div>

                              </a>

                            </div>
                          </div>
                          <div id="category-list-<%= category.id %>"
                               class="row collapse collapse-with-icon-change"><!-- list div-->

                            <% keywords_to_display = current_account ? keywords : keywords.first(7) %>

                            <% keywords_to_display.each do |keyword| %>
                              <%= render partial: 'app/keywords/keyword',
                                         locals:  {
                                             keyword:   keyword,
                                             account:   current_account,
                                             edit_link: true,
                                             add_link:  false
                                         }
                              %>
                            <% end %>

                            <% unless current_account %>
                            <div class="col-12 small pt-2 text-left pl-5">
                              <%= link_to 'More...', community_category_path(category) %>
                            </div>
                            <% end %>

                          </div>
                        </div>
                    <% end %>
                  </div>
                <% end %>

              </div>
            </div>
          </div>
        </div><!--        accordion-->


      </div><!--      col-->
    </div><!--    row-->
  </div>
</section>